web/router.ex
defmodule TecLab.Router do
  use TecLab.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TecLab do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    post "/new", PageController, :new
    get "/new", PageController, :new
    get "/find", FindController, :index
    post "/find/new", FindController, :new
    get "/find/new", FindController, :new
    # resources "/find", FindController, only: [:index, :new]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TecLab do
  #   pipe_through :api
  # end
end

lib/tec_lab/cron_one.ex
defmodule TecLab.CronOne do
  use GenServer

  def start_link do
    GenServer.start_link(__MODULE__, %{})
  end

  def init(state) do
    schedule_work() 
    {:ok, state}
  end

  def handle_info(:work, state) do

    files_found = Redis.all()
    list_File = for n <- files_found do
      IO.inspect n
      file_found = Redis.get(n)
        |> Crypt.de
        |> String.split(",")
      file_found
    end
    csv_content(list_File)
    schedule_work()
    {:noreply, state}
  end

  defp csv_content(list_) do
    raw_csv_content = list_
      |> CSV.encode
      |> Enum.to_list
      |> to_string
      |> IO.inspect

      #TODO: download file 
  end

  defp schedule_work() do
    Process.send_after(self(), :work, 1 * 1 * 60 * 1000) # a minute
  end
end

lib/tec_lab/endpoint.ex
defmodule TecLab.Endpoint do
  use Phoenix.Endpoint, otp_app: :tec_lab

  socket "/socket", TecLab.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :tec_lab, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head


  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_tec_lab_key",
    signing_salt: "Svg9YjWn"

  plug TecLab.Router
end

lib/tec_lab/repo.ex
defmodule TecLab.Repo do
  use Ecto.Repo, otp_app: :tec_lab, adapter: Mongo.Ecto
end

web/controllers/page_controller.ex
defmodule TecLab.PageController do
  use TecLab.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def new(conn, params) do
    file = params["file"]

    if (file["for"].path) do
      # read the file
      file_content = File.read!(file["for"].path)
        # |> String.replace("\"", "")
        |> String.split("\n")
      file_name = file["for"].filename
        
      for n <- file_content do
        file_row = String.split(n, ",")
        file_crypt = Crypt.en(n)
        first = Enum.at(file_row,0)
          |> String.replace("\"", "")
        Redis.set(first, file_crypt)
      end

      render(conn, "success.html",  file: file_name)
    else
      render conn, "index.html"
    end

  end  
end

defmodule TecLab.FindController do
  use TecLab.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def new(conn, params) do
    file_name = params["file_name"]

    if (file_name["for"]) do
      file_found = Redis.get(file_name["for"])
        |> Crypt.de
      if (file_found) do
        render(conn, "success.html", file_found: file_found)
      else
        render conn, "index.html"
      end
    else
      render conn, "index.html"
    end

  end
end

web/views/error_view.ex
defmodule TecLab.ErrorView do
  use TecLab.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/find_view.ex
defmodule TecLab.FindView do
  use TecLab.Web, :view
end

web/views/layout_view.ex
defmodule TecLab.LayoutView do
  use TecLab.Web, :view
end

web/views/page_view.ex
defmodule TecLab.PageView do
  use TecLab.Web, :view
end

web/templates/find/index.html.eex
<%= form_for @conn, find_path(@conn, :new), [as: :file_name], fn f -> %>
  <%= text_input f, :for %>
  <%= submit "Search" %>
<% end %> 

web/templates/find/success.html.eex
<div>
  <%= @file_found %>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello TecLab!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Home</a></li>
            <li><a href="/find">Find</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<%= form_for @conn, page_path(@conn, :new), [as: :file, multipart: true], fn f -> %>
  <%= file_input f, :for %>
  <%= submit "Save" %>
<% end %> 

web/templates/page/success.html.eex
<div>
  Tu archivo se guardo <%= @file %>
</div>